"""Initial migration with all core models

Revision ID: dae9bca9970a
Revises: 
Create Date: 2025-12-12 02:16:19.290001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae9bca9970a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_email'), 'players', ['email'], unique=True)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'ACTIVE', 'FINISHED', name='roomstatus', native_enum=False, length=20), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_code'), 'rooms', ['code'], unique=True)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_status'), 'rooms', ['status'], unique=False)
    op.create_table('projectiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('shooter_player_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('velocity_x', sa.Float(), nullable=False),
    sa.Column('velocity_y', sa.Float(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectiles_id'), 'projectiles', ['id'], unique=False)
    op.create_index(op.f('ix_projectiles_room_id'), 'projectiles', ['room_id'], unique=False)
    op.create_table('room_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('tank_color', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'room_id', name='uq_player_room')
    )
    op.create_index(op.f('ix_room_memberships_id'), 'room_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_room_memberships_player_id'), 'room_memberships', ['player_id'], unique=False)
    op.create_index(op.f('ix_room_memberships_room_id'), 'room_memberships', ['room_id'], unique=False)
    op.create_table('tank_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('velocity_x', sa.Float(), nullable=False),
    sa.Column('velocity_y', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'room_id', name='uq_tank_player_room')
    )
    op.create_index(op.f('ix_tank_states_id'), 'tank_states', ['id'], unique=False)
    op.create_index(op.f('ix_tank_states_player_id'), 'tank_states', ['player_id'], unique=False)
    op.create_index(op.f('ix_tank_states_room_id'), 'tank_states', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tank_states_room_id'), table_name='tank_states')
    op.drop_index(op.f('ix_tank_states_player_id'), table_name='tank_states')
    op.drop_index(op.f('ix_tank_states_id'), table_name='tank_states')
    op.drop_table('tank_states')
    op.drop_index(op.f('ix_room_memberships_room_id'), table_name='room_memberships')
    op.drop_index(op.f('ix_room_memberships_player_id'), table_name='room_memberships')
    op.drop_index(op.f('ix_room_memberships_id'), table_name='room_memberships')
    op.drop_table('room_memberships')
    op.drop_index(op.f('ix_projectiles_room_id'), table_name='projectiles')
    op.drop_index(op.f('ix_projectiles_id'), table_name='projectiles')
    op.drop_table('projectiles')
    op.drop_index(op.f('ix_rooms_status'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_code'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_email'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
